[package]
name = "ntpu-market-research-statistical-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
mimalloc = "0.1.37"
polars = {version = "0.29.0", features = ["csv", "lazy", "describe"]}
pyo3 = {version = "0.18.3", features = ["auto-initialize"]}
pyo3-polars = "0.3.0"
